# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-07-17T23:07:35Z"
  generation: 4
  labels:
    app: hello-kubernetes
  name: hello-kubernetes
  namespace: default
  resourceVersion: "23023"
  uid: d5f5eb74-c43c-4e83-9ce0-062e38c0de42
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  minReadySeconds: 15
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - image: leandrocgsi/hello-kubernetes:erudio-0.0.2
        imagePullPolicy: IfNotPresent
        name: hello-kubernetes
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-07-18T00:10:07Z"
    lastUpdateTime: "2024-07-18T00:10:21Z"
    message: ReplicaSet "hello-kubernetes-7b56cf69f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-07-30T20:15:30Z"
    lastUpdateTime: "2024-07-30T20:15:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
